title: Abigail Santiago
description: Crafting the internet since '99
url: https://neil-b-patel.com

theme: hacked-jekyll
repository: abigailmsanti/tech-website
color_punct: pink-9
color_key: pink-4
color_value: pink-4
color_hover: pink-5

exclude:
  - LICENSE
  - README.md
  - vendor/
  - assets/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
