title: Abigail Santiago
description: Crafting the internet since '99
url: https://neil-b-patel.com

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/
  - assets/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
